ERROR    root:ConfigStarted.py:59 ❌ Error while performing configurator actions: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#cc-app-container-main > div.cc-app-container__main-frame.cc-grid-container > div.cc-app-container__navigation.ng-star-inserted > cc-navigation > nav > div > ul"}
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x561c5e8cd7fa <unknown>
#1 0x561c5e371e90 <unknown>
#2 0x561c5e3c3870 <unknown>
#3 0x561c5e3c3a91 <unknown>
#4 0x561c5e3b7446 <unknown>
#5 0x561c5e3e926d <unknown>
#6 0x561c5e3b72fa <unknown>
#7 0x561c5e3e940e <unknown>
#8 0x561c5e40f135 <unknown>
#9 0x561c5e3e9013 <unknown>
#10 0x561c5e3b5b3b <unknown>
#11 0x561c5e3b67a1 <unknown>
#12 0x561c5e892b9b <unknown>
#13 0x561c5e896a8a <unknown>
#14 0x561c5e87a912 <unknown>
#15 0x561c5e897604 <unknown>
#16 0x561c5e85f74f <unknown>
#17 0x561c5e8bb678 <unknown>
#18 0x561c5e8bb856 <unknown>
#19 0x561c5e8cc666 <unknown>
#20 0x7f931709caa4 <unknown>
#21 0x7f9317129c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_united_kingdom_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gY2FyLWNvbmZpZ3VyYXRvciIsInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTk3ODA2NDEzNC4xNzQ3MTIxNDI0In0sImFub25JZCI6ImM0YzgzMThhMTBkM2E5YjIifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouY28udWsvcGFzc2VuZ2VyY2Fycy9tZXJjZWRlcy1iZW56LWNhcnMvY2FyLWNvbmZpZ3VyYXRvci5odG1sL21vdG9yaXphdGlvbi9DQ2NpL0dCL2VuL0NMQS9TSE9PVElORyUyMEJSQUtFP2ludGVybmFsX3Rlc3Q9dHJ1ZSIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNTgiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiIxNTUxMjgwMTU3OTQzMTQ5IiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x561c5e8cd7fa <unknown>
#1 0x561c5e371e90 <unknown>
#2 0x561c5e359156 <unknown>
#3 0x561c5e357a6a <unknown>
#4 0x561c5e3581cf <unknown>
#5 0x561c5e358124 <unknown>
#6 0x561c5e37611f <unknown>
#7 0x561c5e41b3ca <unknown>
#8 0x561c5e3e9242 <unknown>
#9 0x561c5e40f135 <unknown>
#10 0x561c5e3e9013 <unknown>
#11 0x561c5e3b5b3b <unknown>
#12 0x561c5e3b67a1 <unknown>
#13 0x561c5e892b9b <unknown>
#14 0x561c5e896a8a <unknown>
#15 0x561c5e87a912 <unknown>
#16 0x561c5e897604 <unknown>
#17 0x561c5e85f74f <unknown>
#18 0x561c5e8bb678 <unknown>
#19 0x561c5e8bb856 <unknown>
#20 0x561c5e8cc666 <unknown>
#21 0x7f931709caa4 <unknown>
#22 0x7f9317129c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_united_kingdom_prod?event=eyJpdGVtQWN0aW9uIjpudWxsLCJzb3VyY2UiOnsicGFnZVR5cGUiOiJkZWZhdWx0IiwibG9jYWxlIjoiZW5fR0IiLCJjb250ZW50Wm9uZXMiOltdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56LmNvLnVrL3Bhc3NlbmdlcmNhcnMvbWVyY2VkZXMtYmVuei1jYXJzL2Nhci1jb25maWd1cmF0b3IuaHRtbC9tb3Rvcml6YXRpb24vQ0NjaS9HQi9lbi9DTEEvU0hPT1RJTkclMjBCUkFLRT9pbnRlcm5hbF90ZXN0PXRydWUiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjU4In0sImZsYWdzIjp7InBhZ2VWaWV3Ijp0cnVlfSwidXNlciI6eyJhdHRyaWJ1dGVzIjp7ImdhQ2xpZW50SUQiOiIxOTc4MDY0MTM0LjE3NDcxMjE0MjQifSwiYW5vbklkIjoiYzRjODMxOGExMGQzYTliMiJ9LCJwZXJmb3JtYW5jZSI6eyJzZGtQYXJzZVRpbWUiOjF9LCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9LCJjYXRhbG9nIjp7fSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI3MTczMjU0Nzk1Mjk4ODU3In0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x561c5e8cd7fa <unknown>
#1 0x561c5e371e90 <unknown>
#2 0x561c5e359156 <unknown>
#3 0x561c5e357a6a <unknown>
#4 0x561c5e3581cf <unknown>
#5 0x561c5e358124 <unknown>
#6 0x561c5e37611f <unknown>
#7 0x561c5e41b3ca <unknown>
#8 0x561c5e3e9242 <unknown>
#9 0x561c5e40f135 <unknown>
#10 0x561c5e3e9013 <unknown>
#11 0x561c5e3b5b3b <unknown>
#12 0x561c5e3b67a1 <unknown>
#13 0x561c5e892b9b <unknown>
#14 0x561c5e896a8a <unknown>
#15 0x561c5e87a912 <unknown>
#16 0x561c5e897604 <unknown>
#17 0x561c5e85f74f <unknown>
#18 0x561c5e8bb678 <unknown>
#19 0x561c5e8bb856 <unknown>
#20 0x561c5e8cc666 <unknown>
#21 0x7f931709caa4 <unknown>
#22 0x7f9317129c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:19 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-Allure-Testing/QA-Allure-Testing/Tests/Last Configuration Started_attempt_2.png'
ERROR    root:VerifyPersonalizationAndCapture.py:148 ❌ Image not found in the specified selector. Error: Message: