ERROR    root:ConfigStarted.py:59 ❌ Error while performing configurator actions: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#cc-app-container-main > div.cc-app-container__main-frame.cc-grid-container > div.cc-app-container__navigation.ng-star-inserted > cc-navigation > nav > div > ul"}
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x55bbe34bc7fa <unknown>
#1 0x55bbe2f60e90 <unknown>
#2 0x55bbe2fb2870 <unknown>
#3 0x55bbe2fb2a91 <unknown>
#4 0x55bbe2fa6446 <unknown>
#5 0x55bbe2fd826d <unknown>
#6 0x55bbe2fa62fa <unknown>
#7 0x55bbe2fd840e <unknown>
#8 0x55bbe2ffe135 <unknown>
#9 0x55bbe2fd8013 <unknown>
#10 0x55bbe2fa4b3b <unknown>
#11 0x55bbe2fa57a1 <unknown>
#12 0x55bbe3481b9b <unknown>
#13 0x55bbe3485a8a <unknown>
#14 0x55bbe3469912 <unknown>
#15 0x55bbe3486604 <unknown>
#16 0x55bbe344e74f <unknown>
#17 0x55bbe34aa678 <unknown>
#18 0x55bbe34aa856 <unknown>
#19 0x55bbe34bb666 <unknown>
#20 0x7ff1c269caa4 <unknown>
#21 0x7ff1c2729c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_poland_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gY2FyLWNvbmZpZ3VyYXRvciIsInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTAyMjMzNjU4OS4xNzQ3MTI1NzI5In0sImFub25JZCI6ImNhMjE1YzkzMzY4ZTBhNmIifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnoucGwvcGFzc2VuZ2VyY2Fycy9tZXJjZWRlcy1iZW56LWNhcnMvY2FyLWNvbmZpZ3VyYXRvci5odG1sL21vdG9yaXphdGlvbi9DQ2NpL1BML3BsL0UtS0xBU1NFL1QtTU9ERUxMP2ludGVybmFsX3Rlc3Q9dHJ1ZSIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjUiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwicGVyZm9ybWFuY2UiOnsic2RrUGFyc2VUaW1lIjoxfSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI3NTk2NzM3NzczNjQ3OTUiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x55bbe34bc7fa <unknown>
#1 0x55bbe2f60e90 <unknown>
#2 0x55bbe2f48156 <unknown>
#3 0x55bbe2f46a6a <unknown>
#4 0x55bbe2f471cf <unknown>
#5 0x55bbe2f47124 <unknown>
#6 0x55bbe2f6511f <unknown>
#7 0x55bbe300a3ca <unknown>
#8 0x55bbe2fd8242 <unknown>
#9 0x55bbe2ffe135 <unknown>
#10 0x55bbe2fd8013 <unknown>
#11 0x55bbe2fa4b3b <unknown>
#12 0x55bbe2fa57a1 <unknown>
#13 0x55bbe3481b9b <unknown>
#14 0x55bbe3485a8a <unknown>
#15 0x55bbe3469912 <unknown>
#16 0x55bbe3486604 <unknown>
#17 0x55bbe344e74f <unknown>
#18 0x55bbe34aa678 <unknown>
#19 0x55bbe34aa856 <unknown>
#20 0x55bbe34bb666 <unknown>
#21 0x7ff1c269caa4 <unknown>
#22 0x7ff1c2729c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_poland_prod?event=eyJpdGVtQWN0aW9uIjpudWxsLCJzb3VyY2UiOnsicGFnZVR5cGUiOiJkZWZhdWx0IiwibG9jYWxlIjoicGxfUEwiLCJjb250ZW50Wm9uZXMiOltdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56LnBsL3Bhc3NlbmdlcmNhcnMvbWVyY2VkZXMtYmVuei1jYXJzL2Nhci1jb25maWd1cmF0b3IuaHRtbC9tb3Rvcml6YXRpb24vQ0NjaS9QTC9wbC9FLUtMQVNTRS9ULU1PREVMTD9pbnRlcm5hbF90ZXN0PXRydWUiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjY1In0sImZsYWdzIjp7InBhZ2VWaWV3Ijp0cnVlfSwidXNlciI6eyJhdHRyaWJ1dGVzIjp7ImdhQ2xpZW50SUQiOiIxMDIyMzM2NTg5LjE3NDcxMjU3MjkifSwiYW5vbklkIjoiY2EyMTVjOTMzNjhlMGE2YiJ9LCJwZXJmb3JtYW5jZSI6e30sImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX0sImNhdGFsb2ciOnt9LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjU1Mzk4MDM3NzUyNjA5MzkifQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x55bbe34bc7fa <unknown>
#1 0x55bbe2f60e90 <unknown>
#2 0x55bbe2f48156 <unknown>
#3 0x55bbe2f46a6a <unknown>
#4 0x55bbe2f471cf <unknown>
#5 0x55bbe2f47124 <unknown>
#6 0x55bbe2f6511f <unknown>
#7 0x55bbe300a3ca <unknown>
#8 0x55bbe2fd8242 <unknown>
#9 0x55bbe2ffe135 <unknown>
#10 0x55bbe2fd8013 <unknown>
#11 0x55bbe2fa4b3b <unknown>
#12 0x55bbe2fa57a1 <unknown>
#13 0x55bbe3481b9b <unknown>
#14 0x55bbe3485a8a <unknown>
#15 0x55bbe3469912 <unknown>
#16 0x55bbe3486604 <unknown>
#17 0x55bbe344e74f <unknown>
#18 0x55bbe34aa678 <unknown>
#19 0x55bbe34aa856 <unknown>
#20 0x55bbe34bb666 <unknown>
#21 0x7ff1c269caa4 <unknown>
#22 0x7ff1c2729c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:19 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-Allure-Testing/QA-Allure-Testing/Tests/Last Configuration Started_attempt_2.png'
ERROR    root:VerifyPersonalizationAndCapture.py:148 ❌ Image not found in the specified selector. Error: Message: