ERROR    root:ConfigStarted.py:59 ❌ Error while performing configurator actions: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#cc-app-container-main > div.cc-app-container__main-frame.cc-grid-container > div.cc-app-container__navigation.ng-star-inserted > cc-navigation > nav > div > ul"}
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x55a833e017fa <unknown>
#1 0x55a8338a5e90 <unknown>
#2 0x55a8338f7870 <unknown>
#3 0x55a8338f7a91 <unknown>
#4 0x55a8338eb446 <unknown>
#5 0x55a83391d26d <unknown>
#6 0x55a8338eb2fa <unknown>
#7 0x55a83391d40e <unknown>
#8 0x55a833943135 <unknown>
#9 0x55a83391d013 <unknown>
#10 0x55a8338e9b3b <unknown>
#11 0x55a8338ea7a1 <unknown>
#12 0x55a833dc6b9b <unknown>
#13 0x55a833dcaa8a <unknown>
#14 0x55a833dae912 <unknown>
#15 0x55a833dcb604 <unknown>
#16 0x55a833d9374f <unknown>
#17 0x55a833def678 <unknown>
#18 0x55a833def856 <unknown>
#19 0x55a833e00666 <unknown>
#20 0x7f430be9caa4 <unknown>
#21 0x7f430bf29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_spain_prod?event=eyJpdGVtQWN0aW9uIjpudWxsLCJzb3VyY2UiOnsicGFnZVR5cGUiOiJkZWZhdWx0IiwibG9jYWxlIjoiZXNfRVMiLCJjb250ZW50Wm9uZXMiOltdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56LmVzL3Bhc3NlbmdlcmNhcnMvbWVyY2VkZXMtYmVuei1jYXJzL2Nhci1jb25maWd1cmF0b3IuaHRtbC9tb3Rvcml6YXRpb24vQ0NjaS9FUy9lcy9HTEItS0xBU1NFL09GRlJPQURFUj9pbnRlcm5hbF90ZXN0PXRydWUiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjU2In0sImZsYWdzIjp7InBhZ2VWaWV3Ijp0cnVlfSwidXNlciI6eyJhdHRyaWJ1dGVzIjp7ImdhQ2xpZW50SUQiOiI2MDk0NzMwLjE3NDcxMjA5NDEifSwiYW5vbklkIjoiMjVhMjNkNjY1MzZlZmNhZiJ9LCJwZXJmb3JtYW5jZSI6e30sImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX0sImNhdGFsb2ciOnt9LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6Ijc5NDI1OTk1NzE3ODYwNTgifQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x55a833e017fa <unknown>
#1 0x55a8338a5e90 <unknown>
#2 0x55a83388d156 <unknown>
#3 0x55a83388ba6a <unknown>
#4 0x55a83388c1cf <unknown>
#5 0x55a83388c124 <unknown>
#6 0x55a8338aa11f <unknown>
#7 0x55a83394f3ca <unknown>
#8 0x55a83391d242 <unknown>
#9 0x55a833943135 <unknown>
#10 0x55a83391d013 <unknown>
#11 0x55a8338e9b3b <unknown>
#12 0x55a8338ea7a1 <unknown>
#13 0x55a833dc6b9b <unknown>
#14 0x55a833dcaa8a <unknown>
#15 0x55a833dae912 <unknown>
#16 0x55a833dcb604 <unknown>
#17 0x55a833d9374f <unknown>
#18 0x55a833def678 <unknown>
#19 0x55a833def856 <unknown>
#20 0x55a833e00666 <unknown>
#21 0x7f430be9caa4 <unknown>
#22 0x7f430bf29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_spain_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gY2FyLWNvbmZpZ3VyYXRvciIsInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiNjA5NDczMC4xNzQ3MTIwOTQxIn0sImFub25JZCI6IjI1YTIzZDY2NTM2ZWZjYWYifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouZXMvcGFzc2VuZ2VyY2Fycy9tZXJjZWRlcy1iZW56LWNhcnMvY2FyLWNvbmZpZ3VyYXRvci5odG1sL21vdG9yaXphdGlvbi9DQ2NpL0VTL2VzL0dMQi1LTEFTU0UvT0ZGUk9BREVSP2ludGVybmFsX3Rlc3Q9dHJ1ZSIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNTYiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwicGVyZm9ybWFuY2UiOnsic2RrUGFyc2VUaW1lIjoxfSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI2MzY3MzU4NTA4MjAzNzU2IiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x55a833e017fa <unknown>
#1 0x55a8338a5e90 <unknown>
#2 0x55a83388d156 <unknown>
#3 0x55a83388ba6a <unknown>
#4 0x55a83388c1cf <unknown>
#5 0x55a83388c124 <unknown>
#6 0x55a8338aa11f <unknown>
#7 0x55a83394f3ca <unknown>
#8 0x55a83391d242 <unknown>
#9 0x55a833943135 <unknown>
#10 0x55a83391d013 <unknown>
#11 0x55a8338e9b3b <unknown>
#12 0x55a8338ea7a1 <unknown>
#13 0x55a833dc6b9b <unknown>
#14 0x55a833dcaa8a <unknown>
#15 0x55a833dae912 <unknown>
#16 0x55a833dcb604 <unknown>
#17 0x55a833d9374f <unknown>
#18 0x55a833def678 <unknown>
#19 0x55a833def856 <unknown>
#20 0x55a833e00666 <unknown>
#21 0x7f430be9caa4 <unknown>
#22 0x7f430bf29c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:19 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-Allure-Testing/QA-Allure-Testing/Tests/Last Configuration Started_attempt_2.png'
ERROR    root:VerifyPersonalizationAndCapture.py:148 ❌ Image not found in the specified selector. Error: Message: