ERROR    root:ConfigStarted.py:59 ❌ Error while performing configurator actions: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#cc-app-container-main > div.cc-app-container__main-frame.cc-grid-container > div.cc-app-container__navigation.ng-star-inserted > cc-navigation > nav > div > ul"}
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x561a2bb1a7fa <unknown>
#1 0x561a2b5bee90 <unknown>
#2 0x561a2b610870 <unknown>
#3 0x561a2b610a91 <unknown>
#4 0x561a2b604446 <unknown>
#5 0x561a2b63626d <unknown>
#6 0x561a2b6042fa <unknown>
#7 0x561a2b63640e <unknown>
#8 0x561a2b65c135 <unknown>
#9 0x561a2b636013 <unknown>
#10 0x561a2b602b3b <unknown>
#11 0x561a2b6037a1 <unknown>
#12 0x561a2badfb9b <unknown>
#13 0x561a2bae3a8a <unknown>
#14 0x561a2bac7912 <unknown>
#15 0x561a2bae4604 <unknown>
#16 0x561a2baac74f <unknown>
#17 0x561a2bb08678 <unknown>
#18 0x561a2bb08856 <unknown>
#19 0x561a2bb19666 <unknown>
#20 0x7f0d4609caa4 <unknown>
#21 0x7f0d46129c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_romania_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gY2FyLWNvbmZpZ3VyYXRvciIsInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTI5NTkzOTUzNC4xNzQ3MTI2MzE2In0sImFub25JZCI6ImFlYWYwNzBiMDMxZjllMTIifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnoucm8vcGFzc2VuZ2VyY2Fycy9tZXJjZWRlcy1iZW56LWNhcnMvY2FyLWNvbmZpZ3VyYXRvci5odG1sL21vdG9yaXphdGlvbi9DQ2NpL1JPL3JvL0UtS0xBU1NFL1QtTU9ERUxMP2ludGVybmFsX3Rlc3Q9dHJ1ZSIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjciLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwicGVyZm9ybWFuY2UiOnsic2RrUGFyc2VUaW1lIjoxfSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiIwOTgxNzcxNTI1NjQ0MTMwNiIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x561a2bb1a7fa <unknown>
#1 0x561a2b5bee90 <unknown>
#2 0x561a2b5a6156 <unknown>
#3 0x561a2b5a4a6a <unknown>
#4 0x561a2b5a51cf <unknown>
#5 0x561a2b5a5124 <unknown>
#6 0x561a2b5c311f <unknown>
#7 0x561a2b6683ca <unknown>
#8 0x561a2b636242 <unknown>
#9 0x561a2b65c135 <unknown>
#10 0x561a2b636013 <unknown>
#11 0x561a2b602b3b <unknown>
#12 0x561a2b6037a1 <unknown>
#13 0x561a2badfb9b <unknown>
#14 0x561a2bae3a8a <unknown>
#15 0x561a2bac7912 <unknown>
#16 0x561a2bae4604 <unknown>
#17 0x561a2baac74f <unknown>
#18 0x561a2bb08678 <unknown>
#19 0x561a2bb08856 <unknown>
#20 0x561a2bb19666 <unknown>
#21 0x7f0d4609caa4 <unknown>
#22 0x7f0d46129c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_romania_prod?event=eyJpdGVtQWN0aW9uIjpudWxsLCJzb3VyY2UiOnsicGFnZVR5cGUiOiJkZWZhdWx0IiwibG9jYWxlIjoicm9fUk8iLCJjb250ZW50Wm9uZXMiOltdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56LnJvL3Bhc3NlbmdlcmNhcnMvbWVyY2VkZXMtYmVuei1jYXJzL2Nhci1jb25maWd1cmF0b3IuaHRtbC9tb3Rvcml6YXRpb24vQ0NjaS9STy9yby9FLUtMQVNTRS9ULU1PREVMTD9pbnRlcm5hbF90ZXN0PXRydWUiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjY3In0sImZsYWdzIjp7InBhZ2VWaWV3Ijp0cnVlfSwidXNlciI6eyJhdHRyaWJ1dGVzIjp7ImdhQ2xpZW50SUQiOiIxMjk1OTM5NTM0LjE3NDcxMjYzMTYifSwiYW5vbklkIjoiYWVhZjA3MGIwMzFmOWUxMiJ9LCJwZXJmb3JtYW5jZSI6e30sImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX0sImNhdGFsb2ciOnt9LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjY5MDg1NzM4MjA1NDM5NDIifQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x561a2bb1a7fa <unknown>
#1 0x561a2b5bee90 <unknown>
#2 0x561a2b5a6156 <unknown>
#3 0x561a2b5a4a6a <unknown>
#4 0x561a2b5a51cf <unknown>
#5 0x561a2b5a5124 <unknown>
#6 0x561a2b5c311f <unknown>
#7 0x561a2b6683ca <unknown>
#8 0x561a2b636242 <unknown>
#9 0x561a2b65c135 <unknown>
#10 0x561a2b636013 <unknown>
#11 0x561a2b602b3b <unknown>
#12 0x561a2b6037a1 <unknown>
#13 0x561a2badfb9b <unknown>
#14 0x561a2bae3a8a <unknown>
#15 0x561a2bac7912 <unknown>
#16 0x561a2bae4604 <unknown>
#17 0x561a2baac74f <unknown>
#18 0x561a2bb08678 <unknown>
#19 0x561a2bb08856 <unknown>
#20 0x561a2bb19666 <unknown>
#21 0x7f0d4609caa4 <unknown>
#22 0x7f0d46129c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:19 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-Allure-Testing/QA-Allure-Testing/Tests/Last Configuration Started_attempt_2.png'
ERROR    root:VerifyPersonalizationAndCapture.py:148 ❌ Image not found in the specified selector. Error: Message: