ERROR    root:ConfigCompleted.py:57 ❌ Error while performing configurator actions: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#cc-app-container-main > div.cc-app-container__main-frame.cc-grid-container > div.cc-app-container__navigation.ng-star-inserted > cc-navigation > nav > div > ul"}
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x55c7e0f5a7fa <unknown>
#1 0x55c7e09fee90 <unknown>
#2 0x55c7e0a50870 <unknown>
#3 0x55c7e0a50a91 <unknown>
#4 0x55c7e0a44446 <unknown>
#5 0x55c7e0a7626d <unknown>
#6 0x55c7e0a442fa <unknown>
#7 0x55c7e0a7640e <unknown>
#8 0x55c7e0a9c135 <unknown>
#9 0x55c7e0a76013 <unknown>
#10 0x55c7e0a42b3b <unknown>
#11 0x55c7e0a437a1 <unknown>
#12 0x55c7e0f1fb9b <unknown>
#13 0x55c7e0f23a8a <unknown>
#14 0x55c7e0f07912 <unknown>
#15 0x55c7e0f24604 <unknown>
#16 0x55c7e0eec74f <unknown>
#17 0x55c7e0f48678 <unknown>
#18 0x55c7e0f48856 <unknown>
#19 0x55c7e0f59666 <unknown>
#20 0x7f716549caa4 <unknown>
#21 0x7f7165529c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_romania_prod?event=eyJpdGVtQWN0aW9uIjpudWxsLCJzb3VyY2UiOnsicGFnZVR5cGUiOiJkZWZhdWx0IiwibG9jYWxlIjoicm9fUk8iLCJjb250ZW50Wm9uZXMiOltdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56LnJvL3Bhc3NlbmdlcmNhcnMvbWVyY2VkZXMtYmVuei1jYXJzL2Nhci1jb25maWd1cmF0b3IuaHRtbC9tb3Rvcml6YXRpb24vQ0NjaS9STy9yby9DTEEvQ09VUEU%2FaW50ZXJuYWxfdGVzdD10cnVlIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2NyJ9LCJmbGFncyI6eyJwYWdlVmlldyI6dHJ1ZX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTYzNjYwMjY2MC4xNzQ3MTM2ODIyIn0sImFub25JZCI6ImUyNzMzMGM2YWVkMWJjYTUifSwicGVyZm9ybWFuY2UiOnt9LCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9LCJjYXRhbG9nIjp7fSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI2MDg0MzYzMzQwODgyODkifQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x55c7e0f5a7fa <unknown>
#1 0x55c7e09fee90 <unknown>
#2 0x55c7e09e6156 <unknown>
#3 0x55c7e09e4a6a <unknown>
#4 0x55c7e09e51cf <unknown>
#5 0x55c7e09e5124 <unknown>
#6 0x55c7e0a0311f <unknown>
#7 0x55c7e0aa83ca <unknown>
#8 0x55c7e0a76242 <unknown>
#9 0x55c7e0a9c135 <unknown>
#10 0x55c7e0a76013 <unknown>
#11 0x55c7e0a42b3b <unknown>
#12 0x55c7e0a437a1 <unknown>
#13 0x55c7e0f1fb9b <unknown>
#14 0x55c7e0f23a8a <unknown>
#15 0x55c7e0f07912 <unknown>
#16 0x55c7e0f24604 <unknown>
#17 0x55c7e0eec74f <unknown>
#18 0x55c7e0f48678 <unknown>
#19 0x55c7e0f48856 <unknown>
#20 0x55c7e0f59666 <unknown>
#21 0x7f716549caa4 <unknown>
#22 0x7f7165529c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_romania_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gY2FyLWNvbmZpZ3VyYXRvciIsInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTYzNjYwMjY2MC4xNzQ3MTM2ODIyIn0sImFub25JZCI6ImUyNzMzMGM2YWVkMWJjYTUifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnoucm8vcGFzc2VuZ2VyY2Fycy9tZXJjZWRlcy1iZW56LWNhcnMvY2FyLWNvbmZpZ3VyYXRvci5odG1sL21vdG9yaXphdGlvbi9DQ2NpL1JPL3JvL0NMQS9DT1VQRT9pbnRlcm5hbF90ZXN0PXRydWUiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjY3IiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sInBlcmZvcm1hbmNlIjp7InNka1BhcnNlVGltZSI6MX0sIl90b29sc0V2ZW50TGlua0lkIjoiNjE3NzIyNDg1MTM5NTMwNSIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x55c7e0f5a7fa <unknown>
#1 0x55c7e09fee90 <unknown>
#2 0x55c7e09e6156 <unknown>
#3 0x55c7e09e4a6a <unknown>
#4 0x55c7e09e51cf <unknown>
#5 0x55c7e09e5124 <unknown>
#6 0x55c7e0a0311f <unknown>
#7 0x55c7e0aa83ca <unknown>
#8 0x55c7e0a76242 <unknown>
#9 0x55c7e0a9c135 <unknown>
#10 0x55c7e0a76013 <unknown>
#11 0x55c7e0a42b3b <unknown>
#12 0x55c7e0a437a1 <unknown>
#13 0x55c7e0f1fb9b <unknown>
#14 0x55c7e0f23a8a <unknown>
#15 0x55c7e0f07912 <unknown>
#16 0x55c7e0f24604 <unknown>
#17 0x55c7e0eec74f <unknown>
#18 0x55c7e0f48678 <unknown>
#19 0x55c7e0f48856 <unknown>
#20 0x55c7e0f59666 <unknown>
#21 0x7f716549caa4 <unknown>
#22 0x7f7165529c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:19 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-Allure-Testing/QA-Allure-Testing/Tests/Last Configuration Completed_attempt_2.png'
ERROR    root:VerifyPersonalizationAndCapture.py:148 ❌ Image not found in the specified selector. Error: Message: