ERROR    root:ConfigCompleted.py:57 ❌ Error while performing configurator actions: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#cc-app-container-main > div.cc-app-container__main-frame.cc-grid-container > div.cc-app-container__navigation.ng-star-inserted > cc-navigation > nav > div > ul"}
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x55c7fc36e7fa <unknown>
#1 0x55c7fbe12e90 <unknown>
#2 0x55c7fbe64870 <unknown>
#3 0x55c7fbe64a91 <unknown>
#4 0x55c7fbe58446 <unknown>
#5 0x55c7fbe8a26d <unknown>
#6 0x55c7fbe582fa <unknown>
#7 0x55c7fbe8a40e <unknown>
#8 0x55c7fbeb0135 <unknown>
#9 0x55c7fbe8a013 <unknown>
#10 0x55c7fbe56b3b <unknown>
#11 0x55c7fbe577a1 <unknown>
#12 0x55c7fc333b9b <unknown>
#13 0x55c7fc337a8a <unknown>
#14 0x55c7fc31b912 <unknown>
#15 0x55c7fc338604 <unknown>
#16 0x55c7fc30074f <unknown>
#17 0x55c7fc35c678 <unknown>
#18 0x55c7fc35c856 <unknown>
#19 0x55c7fc36d666 <unknown>
#20 0x7f050809caa4 <unknown>
#21 0x7f0508129c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_spain_prod?event=eyJpdGVtQWN0aW9uIjpudWxsLCJzb3VyY2UiOnsicGFnZVR5cGUiOiJkZWZhdWx0IiwibG9jYWxlIjoiZXNfRVMiLCJjb250ZW50Wm9uZXMiOltdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56LmVzL3Bhc3NlbmdlcmNhcnMvbWVyY2VkZXMtYmVuei1jYXJzL2Nhci1jb25maWd1cmF0b3IuaHRtbC9tb3Rvcml6YXRpb24vQ0NjaS9FUy9lcy9TTC1LTEFTU0UvUk9BRFNURVI%2FaW50ZXJuYWxfdGVzdD10cnVlIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI1NiJ9LCJmbGFncyI6eyJwYWdlVmlldyI6dHJ1ZX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTYxNDM3NDM0OC4xNzQ3MTI5ODg4In0sImFub25JZCI6IjFhNTg4ZGQ1MTVjOGYwNTQifSwicGVyZm9ybWFuY2UiOnt9LCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9LCJjYXRhbG9nIjp7fSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiIxMzQxMTc4MzkzODI1Mjg2NCJ9: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x55c7fc36e7fa <unknown>
#1 0x55c7fbe12e90 <unknown>
#2 0x55c7fbdfa156 <unknown>
#3 0x55c7fbdf8a6a <unknown>
#4 0x55c7fbdf91cf <unknown>
#5 0x55c7fbdf9124 <unknown>
#6 0x55c7fbe1711f <unknown>
#7 0x55c7fbebc3ca <unknown>
#8 0x55c7fbe8a242 <unknown>
#9 0x55c7fbeb0135 <unknown>
#10 0x55c7fbe8a013 <unknown>
#11 0x55c7fbe56b3b <unknown>
#12 0x55c7fbe577a1 <unknown>
#13 0x55c7fc333b9b <unknown>
#14 0x55c7fc337a8a <unknown>
#15 0x55c7fc31b912 <unknown>
#16 0x55c7fc338604 <unknown>
#17 0x55c7fc30074f <unknown>
#18 0x55c7fc35c678 <unknown>
#19 0x55c7fc35c856 <unknown>
#20 0x55c7fc36d666 <unknown>
#21 0x7f050809caa4 <unknown>
#22 0x7f0508129c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_spain_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gY2FyLWNvbmZpZ3VyYXRvciIsInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTYxNDM3NDM0OC4xNzQ3MTI5ODg4In0sImFub25JZCI6IjFhNTg4ZGQ1MTVjOGYwNTQifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouZXMvcGFzc2VuZ2VyY2Fycy9tZXJjZWRlcy1iZW56LWNhcnMvY2FyLWNvbmZpZ3VyYXRvci5odG1sL21vdG9yaXphdGlvbi9DQ2NpL0VTL2VzL1NMLUtMQVNTRS9ST0FEU1RFUj9pbnRlcm5hbF90ZXN0PXRydWUiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjU2IiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sInBlcmZvcm1hbmNlIjp7InNka1BhcnNlVGltZSI6MX0sIl90b29sc0V2ZW50TGlua0lkIjoiNDcxMjAxMDMzOTE3NjEzNyIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x55c7fc36e7fa <unknown>
#1 0x55c7fbe12e90 <unknown>
#2 0x55c7fbdfa156 <unknown>
#3 0x55c7fbdf8a6a <unknown>
#4 0x55c7fbdf91cf <unknown>
#5 0x55c7fbdf9124 <unknown>
#6 0x55c7fbe1711f <unknown>
#7 0x55c7fbebc3ca <unknown>
#8 0x55c7fbe8a242 <unknown>
#9 0x55c7fbeb0135 <unknown>
#10 0x55c7fbe8a013 <unknown>
#11 0x55c7fbe56b3b <unknown>
#12 0x55c7fbe577a1 <unknown>
#13 0x55c7fc333b9b <unknown>
#14 0x55c7fc337a8a <unknown>
#15 0x55c7fc31b912 <unknown>
#16 0x55c7fc338604 <unknown>
#17 0x55c7fc30074f <unknown>
#18 0x55c7fc35c678 <unknown>
#19 0x55c7fc35c856 <unknown>
#20 0x55c7fc36d666 <unknown>
#21 0x7f050809caa4 <unknown>
#22 0x7f0508129c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:19 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-Allure-Testing/QA-Allure-Testing/Tests/Last Configuration Completed_attempt_2.png'
ERROR    root:VerifyPersonalizationAndCapture.py:148 ❌ Image not found in the specified selector. Error: Message: