ERROR    root:ConfigCompleted.py:57 ❌ Error while performing configurator actions: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#cc-app-container-main > div.cc-app-container__main-frame.cc-grid-container > div.cc-app-container__navigation.ng-star-inserted > cc-navigation > nav > div > ul"}
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x55f5d843e7fa <unknown>
#1 0x55f5d7ee2e90 <unknown>
#2 0x55f5d7f34870 <unknown>
#3 0x55f5d7f34a91 <unknown>
#4 0x55f5d7f28446 <unknown>
#5 0x55f5d7f5a26d <unknown>
#6 0x55f5d7f282fa <unknown>
#7 0x55f5d7f5a40e <unknown>
#8 0x55f5d7f80135 <unknown>
#9 0x55f5d7f5a013 <unknown>
#10 0x55f5d7f26b3b <unknown>
#11 0x55f5d7f277a1 <unknown>
#12 0x55f5d8403b9b <unknown>
#13 0x55f5d8407a8a <unknown>
#14 0x55f5d83eb912 <unknown>
#15 0x55f5d8408604 <unknown>
#16 0x55f5d83d074f <unknown>
#17 0x55f5d842c678 <unknown>
#18 0x55f5d842c856 <unknown>
#19 0x55f5d843d666 <unknown>
#20 0x7f9b0909caa4 <unknown>
#21 0x7f9b09129c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_luxembourg_prod?event=eyJpdGVtQWN0aW9uIjpudWxsLCJzb3VyY2UiOnsicGFnZVR5cGUiOiJkZWZhdWx0IiwibG9jYWxlIjoiZGVfTFUiLCJjb250ZW50Wm9uZXMiOltdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lmx1L2RlL3Bhc3NlbmdlcmNhcnMvbWVyY2VkZXMtYmVuei1jYXJzL2Nhci1jb25maWd1cmF0b3IuaHRtbC9tb3Rvcml6YXRpb24vQ0NjaS9MVS9kZS9FUVMtS0xBU1NFL0xJTU9VU0lORV9MQU5HP2ludGVybmFsX3Rlc3Q9dHJ1ZSIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNTUifSwiZmxhZ3MiOnsicGFnZVZpZXciOnRydWV9LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjE4MTAwNTc3MC4xNzQ3MTMyMzA2In0sImFub25JZCI6IjA5MzJmMzhkNzNiMjZlZWEifSwicGVyZm9ybWFuY2UiOnt9LCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9LCJjYXRhbG9nIjp7fSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiIxMjk5NjIyOTI2MjEwMTYzMyJ9: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x55f5d843e7fa <unknown>
#1 0x55f5d7ee2e90 <unknown>
#2 0x55f5d7eca156 <unknown>
#3 0x55f5d7ec8a6a <unknown>
#4 0x55f5d7ec91cf <unknown>
#5 0x55f5d7ec9124 <unknown>
#6 0x55f5d7ee711f <unknown>
#7 0x55f5d7f8c3ca <unknown>
#8 0x55f5d7f5a242 <unknown>
#9 0x55f5d7f80135 <unknown>
#10 0x55f5d7f5a013 <unknown>
#11 0x55f5d7f26b3b <unknown>
#12 0x55f5d7f277a1 <unknown>
#13 0x55f5d8403b9b <unknown>
#14 0x55f5d8407a8a <unknown>
#15 0x55f5d83eb912 <unknown>
#16 0x55f5d8408604 <unknown>
#17 0x55f5d83d074f <unknown>
#18 0x55f5d842c678 <unknown>
#19 0x55f5d842c856 <unknown>
#20 0x55f5d843d666 <unknown>
#21 0x7f9b0909caa4 <unknown>
#22 0x7f9b09129c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_luxembourg_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gY2FyLWNvbmZpZ3VyYXRvciIsInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTgxMDA1NzcwLjE3NDcxMzIzMDYifSwiYW5vbklkIjoiMDkzMmYzOGQ3M2IyNmVlYSJ9LCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5sdS9kZS9wYXNzZW5nZXJjYXJzL21lcmNlZGVzLWJlbnotY2Fycy9jYXItY29uZmlndXJhdG9yLmh0bWwvbW90b3JpemF0aW9uL0NDY2kvTFUvZGUvRVFTLUtMQVNTRS9MSU1PVVNJTkVfTEFORz9pbnRlcm5hbF90ZXN0PXRydWUiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjU1IiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sInBlcmZvcm1hbmNlIjp7InNka1BhcnNlVGltZSI6MX0sIl90b29sc0V2ZW50TGlua0lkIjoiNzQwNzc0MDI1MjMzMDgzMiIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x55f5d843e7fa <unknown>
#1 0x55f5d7ee2e90 <unknown>
#2 0x55f5d7eca156 <unknown>
#3 0x55f5d7ec8a6a <unknown>
#4 0x55f5d7ec91cf <unknown>
#5 0x55f5d7ec9124 <unknown>
#6 0x55f5d7ee711f <unknown>
#7 0x55f5d7f8c3ca <unknown>
#8 0x55f5d7f5a242 <unknown>
#9 0x55f5d7f80135 <unknown>
#10 0x55f5d7f5a013 <unknown>
#11 0x55f5d7f26b3b <unknown>
#12 0x55f5d7f277a1 <unknown>
#13 0x55f5d8403b9b <unknown>
#14 0x55f5d8407a8a <unknown>
#15 0x55f5d83eb912 <unknown>
#16 0x55f5d8408604 <unknown>
#17 0x55f5d83d074f <unknown>
#18 0x55f5d842c678 <unknown>
#19 0x55f5d842c856 <unknown>
#20 0x55f5d843d666 <unknown>
#21 0x7f9b0909caa4 <unknown>
#22 0x7f9b09129c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:19 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-Allure-Testing/QA-Allure-Testing/Tests/Last Configuration Completed_attempt_2.png'
ERROR    root:VerifyPersonalizationAndCapture.py:148 ❌ Image not found in the specified selector. Error: Message: