ERROR    root:ConfigCompleted.py:57 ❌ Error while performing configurator actions: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#cc-app-container-main > div.cc-app-container__main-frame.cc-grid-container > div.cc-app-container__navigation.ng-star-inserted > cc-navigation > nav > div > ul"}
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x55e6a5c107fa <unknown>
#1 0x55e6a56b4e90 <unknown>
#2 0x55e6a5706870 <unknown>
#3 0x55e6a5706a91 <unknown>
#4 0x55e6a56fa446 <unknown>
#5 0x55e6a572c26d <unknown>
#6 0x55e6a56fa2fa <unknown>
#7 0x55e6a572c40e <unknown>
#8 0x55e6a5752135 <unknown>
#9 0x55e6a572c013 <unknown>
#10 0x55e6a56f8b3b <unknown>
#11 0x55e6a56f97a1 <unknown>
#12 0x55e6a5bd5b9b <unknown>
#13 0x55e6a5bd9a8a <unknown>
#14 0x55e6a5bbd912 <unknown>
#15 0x55e6a5bda604 <unknown>
#16 0x55e6a5ba274f <unknown>
#17 0x55e6a5bfe678 <unknown>
#18 0x55e6a5bfe856 <unknown>
#19 0x55e6a5c0f666 <unknown>
#20 0x7fd8e249caa4 <unknown>
#21 0x7fd8e2529c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_france_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gY2FyLWNvbmZpZ3VyYXRvciIsInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiNTE5MTQ3NDYuMTc0NzEyOTY3NSJ9LCJhbm9uSWQiOiJlOTgwOTljOGM4NWQ1MGU1In0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56LmZyL3Bhc3NlbmdlcmNhcnMvbWVyY2VkZXMtYmVuei1jYXJzL2Nhci1jb25maWd1cmF0b3IuaHRtbC9tb3Rvcml6YXRpb24vQ0NjaS9GUi9mci9CLUtMQVNTRS9TUE9SVFMlMjBUT1VSRVI%2FaW50ZXJuYWxfdGVzdD10cnVlIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJwZXJmb3JtYW5jZSI6eyJzZGtQYXJzZVRpbWUiOjF9LCJfdG9vbHNFdmVudExpbmtJZCI6IjU2NjM1NDI4MTg3Mjk1MjciLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x55e6a5c107fa <unknown>
#1 0x55e6a56b4e90 <unknown>
#2 0x55e6a569c156 <unknown>
#3 0x55e6a569aa6a <unknown>
#4 0x55e6a569b1cf <unknown>
#5 0x55e6a569b124 <unknown>
#6 0x55e6a56b911f <unknown>
#7 0x55e6a575e3ca <unknown>
#8 0x55e6a572c242 <unknown>
#9 0x55e6a5752135 <unknown>
#10 0x55e6a572c013 <unknown>
#11 0x55e6a56f8b3b <unknown>
#12 0x55e6a56f97a1 <unknown>
#13 0x55e6a5bd5b9b <unknown>
#14 0x55e6a5bd9a8a <unknown>
#15 0x55e6a5bbd912 <unknown>
#16 0x55e6a5bda604 <unknown>
#17 0x55e6a5ba274f <unknown>
#18 0x55e6a5bfe678 <unknown>
#19 0x55e6a5bfe856 <unknown>
#20 0x55e6a5c0f666 <unknown>
#21 0x7fd8e249caa4 <unknown>
#22 0x7fd8e2529c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_france_prod?event=eyJpdGVtQWN0aW9uIjpudWxsLCJzb3VyY2UiOnsicGFnZVR5cGUiOiJkZWZhdWx0IiwibG9jYWxlIjoiZnJfTFUiLCJjb250ZW50Wm9uZXMiOltdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56LmZyL3Bhc3NlbmdlcmNhcnMvbWVyY2VkZXMtYmVuei1jYXJzL2Nhci1jb25maWd1cmF0b3IuaHRtbC9tb3Rvcml6YXRpb24vQ0NjaS9GUi9mci9CLUtMQVNTRS9TUE9SVFMlMjBUT1VSRVI%2FaW50ZXJuYWxfdGVzdD10cnVlIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyJ9LCJmbGFncyI6eyJwYWdlVmlldyI6dHJ1ZX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiNTE5MTQ3NDYuMTc0NzEyOTY3NSJ9LCJhbm9uSWQiOiJlOTgwOTljOGM4NWQ1MGU1In0sInBlcmZvcm1hbmNlIjp7fSwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfSwiY2F0YWxvZyI6e30sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiNDAzOTgzMjcxNzY5NjgyNCJ9: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x55e6a5c107fa <unknown>
#1 0x55e6a56b4e90 <unknown>
#2 0x55e6a569c156 <unknown>
#3 0x55e6a569aa6a <unknown>
#4 0x55e6a569b1cf <unknown>
#5 0x55e6a569b124 <unknown>
#6 0x55e6a56b911f <unknown>
#7 0x55e6a575e3ca <unknown>
#8 0x55e6a572c242 <unknown>
#9 0x55e6a5752135 <unknown>
#10 0x55e6a572c013 <unknown>
#11 0x55e6a56f8b3b <unknown>
#12 0x55e6a56f97a1 <unknown>
#13 0x55e6a5bd5b9b <unknown>
#14 0x55e6a5bd9a8a <unknown>
#15 0x55e6a5bbd912 <unknown>
#16 0x55e6a5bda604 <unknown>
#17 0x55e6a5ba274f <unknown>
#18 0x55e6a5bfe678 <unknown>
#19 0x55e6a5bfe856 <unknown>
#20 0x55e6a5c0f666 <unknown>
#21 0x7fd8e249caa4 <unknown>
#22 0x7fd8e2529c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:19 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-Allure-Testing/QA-Allure-Testing/Tests/Last Configuration Completed_attempt_2.png'
ERROR    root:VerifyPersonalizationAndCapture.py:148 ❌ Image not found in the specified selector. Error: Message: