ERROR    root:ConfigCompleted.py:57 ❌ Error while performing configurator actions: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#cc-app-container-main > div.cc-app-container__main-frame.cc-grid-container > div.cc-app-container__navigation.ng-star-inserted > cc-navigation > nav > div > ul"}
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x562e360b47fa <unknown>
#1 0x562e35b58e90 <unknown>
#2 0x562e35baa870 <unknown>
#3 0x562e35baaa91 <unknown>
#4 0x562e35b9e446 <unknown>
#5 0x562e35bd026d <unknown>
#6 0x562e35b9e2fa <unknown>
#7 0x562e35bd040e <unknown>
#8 0x562e35bf6135 <unknown>
#9 0x562e35bd0013 <unknown>
#10 0x562e35b9cb3b <unknown>
#11 0x562e35b9d7a1 <unknown>
#12 0x562e36079b9b <unknown>
#13 0x562e3607da8a <unknown>
#14 0x562e36061912 <unknown>
#15 0x562e3607e604 <unknown>
#16 0x562e3604674f <unknown>
#17 0x562e360a2678 <unknown>
#18 0x562e360a2856 <unknown>
#19 0x562e360b3666 <unknown>
#20 0x7fce5b29caa4 <unknown>
#21 0x7fce5b329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_united_kingdom_prod?event=eyJpdGVtQWN0aW9uIjpudWxsLCJzb3VyY2UiOnsicGFnZVR5cGUiOiJkZWZhdWx0IiwibG9jYWxlIjoiZW5fR0IiLCJjb250ZW50Wm9uZXMiOltdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56LmNvLnVrL3Bhc3NlbmdlcmNhcnMvbWVyY2VkZXMtYmVuei1jYXJzL2Nhci1jb25maWd1cmF0b3IuaHRtbC9tb3Rvcml6YXRpb24vQ0NjaS9HQi9lbi9DTEEvQ09VUEU%2FaW50ZXJuYWxfdGVzdD10cnVlIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI1OCJ9LCJmbGFncyI6eyJwYWdlVmlldyI6dHJ1ZX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTgyODMzNzA3OC4xNzQ3MTI4ODgxIn0sImFub25JZCI6Ijc5YTZjYjIyMDk4Y2NhMmQifSwicGVyZm9ybWFuY2UiOnt9LCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9LCJjYXRhbG9nIjp7fSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiIyOTY0MjM4NjAzOTk2NTg3MyJ9: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x562e360b47fa <unknown>
#1 0x562e35b58e90 <unknown>
#2 0x562e35b40156 <unknown>
#3 0x562e35b3ea6a <unknown>
#4 0x562e35b3f1cf <unknown>
#5 0x562e35b3f124 <unknown>
#6 0x562e35b5d11f <unknown>
#7 0x562e35c023ca <unknown>
#8 0x562e35bd0242 <unknown>
#9 0x562e35bf6135 <unknown>
#10 0x562e35bd0013 <unknown>
#11 0x562e35b9cb3b <unknown>
#12 0x562e35b9d7a1 <unknown>
#13 0x562e36079b9b <unknown>
#14 0x562e3607da8a <unknown>
#15 0x562e36061912 <unknown>
#16 0x562e3607e604 <unknown>
#17 0x562e3604674f <unknown>
#18 0x562e360a2678 <unknown>
#19 0x562e360a2856 <unknown>
#20 0x562e360b3666 <unknown>
#21 0x7fce5b29caa4 <unknown>
#22 0x7fce5b329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_united_kingdom_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gY2FyLWNvbmZpZ3VyYXRvciIsInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTgyODMzNzA3OC4xNzQ3MTI4ODgxIn0sImFub25JZCI6Ijc5YTZjYjIyMDk4Y2NhMmQifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouY28udWsvcGFzc2VuZ2VyY2Fycy9tZXJjZWRlcy1iZW56LWNhcnMvY2FyLWNvbmZpZ3VyYXRvci5odG1sL21vdG9yaXphdGlvbi9DQ2NpL0dCL2VuL0NMQS9DT1VQRT9pbnRlcm5hbF90ZXN0PXRydWUiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjU4IiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sInBlcmZvcm1hbmNlIjp7InNka1BhcnNlVGltZSI6Mn0sIl90b29sc0V2ZW50TGlua0lkIjoiODQyNTI3Mzk1Mjg1OTc2OSIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x562e360b47fa <unknown>
#1 0x562e35b58e90 <unknown>
#2 0x562e35b40156 <unknown>
#3 0x562e35b3ea6a <unknown>
#4 0x562e35b3f1cf <unknown>
#5 0x562e35b3f124 <unknown>
#6 0x562e35b5d11f <unknown>
#7 0x562e35c023ca <unknown>
#8 0x562e35bd0242 <unknown>
#9 0x562e35bf6135 <unknown>
#10 0x562e35bd0013 <unknown>
#11 0x562e35b9cb3b <unknown>
#12 0x562e35b9d7a1 <unknown>
#13 0x562e36079b9b <unknown>
#14 0x562e3607da8a <unknown>
#15 0x562e36061912 <unknown>
#16 0x562e3607e604 <unknown>
#17 0x562e3604674f <unknown>
#18 0x562e360a2678 <unknown>
#19 0x562e360a2856 <unknown>
#20 0x562e360b3666 <unknown>
#21 0x7fce5b29caa4 <unknown>
#22 0x7fce5b329c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:19 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-Allure-Testing/QA-Allure-Testing/Tests/Last Configuration Completed_attempt_2.png'
ERROR    root:VerifyPersonalizationAndCapture.py:148 ❌ Image not found in the specified selector. Error: Message: