ERROR    root:ConfigCompleted.py:57 ❌ Error while performing configurator actions: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#cc-app-container-main > div.cc-app-container__main-frame.cc-grid-container > div.cc-app-container__navigation.ng-star-inserted > cc-navigation > nav > div > ul"}
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x55f33640a7fa <unknown>
#1 0x55f335eaee90 <unknown>
#2 0x55f335f00870 <unknown>
#3 0x55f335f00a91 <unknown>
#4 0x55f335ef4446 <unknown>
#5 0x55f335f2626d <unknown>
#6 0x55f335ef42fa <unknown>
#7 0x55f335f2640e <unknown>
#8 0x55f335f4c135 <unknown>
#9 0x55f335f26013 <unknown>
#10 0x55f335ef2b3b <unknown>
#11 0x55f335ef37a1 <unknown>
#12 0x55f3363cfb9b <unknown>
#13 0x55f3363d3a8a <unknown>
#14 0x55f3363b7912 <unknown>
#15 0x55f3363d4604 <unknown>
#16 0x55f33639c74f <unknown>
#17 0x55f3363f8678 <unknown>
#18 0x55f3363f8856 <unknown>
#19 0x55f336409666 <unknown>
#20 0x7f711f29caa4 <unknown>
#21 0x7f711f329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_czechia_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gY2FyLWNvbmZpZ3VyYXRvciIsInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTM4MjAyMDgxOC4xNzQ3MTI5NDI5In0sImFub25JZCI6IjFjMGM1YmJjOTA3ZTI0MmEifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouY3ovcGFzc2VuZ2VyY2Fycy9tZXJjZWRlcy1iZW56LWNhcnMvY2FyLWNvbmZpZ3VyYXRvci5odG1sL21vdG9yaXphdGlvbi9DQ2NpL0NaL2NzL0dMQi1LTEFTU0UvT0ZGUk9BREVSP2ludGVybmFsX3Rlc3Q9dHJ1ZSIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjUiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwicGVyZm9ybWFuY2UiOnsic2RrUGFyc2VUaW1lIjoyfSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiIzNjA0MzQ3NTkyNjA4MzczNSIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x55f33640a7fa <unknown>
#1 0x55f335eaee90 <unknown>
#2 0x55f335e96156 <unknown>
#3 0x55f335e94a6a <unknown>
#4 0x55f335e951cf <unknown>
#5 0x55f335e95124 <unknown>
#6 0x55f335eb311f <unknown>
#7 0x55f335f583ca <unknown>
#8 0x55f335f26242 <unknown>
#9 0x55f335f4c135 <unknown>
#10 0x55f335f26013 <unknown>
#11 0x55f335ef2b3b <unknown>
#12 0x55f335ef37a1 <unknown>
#13 0x55f3363cfb9b <unknown>
#14 0x55f3363d3a8a <unknown>
#15 0x55f3363b7912 <unknown>
#16 0x55f3363d4604 <unknown>
#17 0x55f33639c74f <unknown>
#18 0x55f3363f8678 <unknown>
#19 0x55f3363f8856 <unknown>
#20 0x55f336409666 <unknown>
#21 0x7f711f29caa4 <unknown>
#22 0x7f711f329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_czechia_prod?event=eyJpdGVtQWN0aW9uIjpudWxsLCJzb3VyY2UiOnsicGFnZVR5cGUiOiJkZWZhdWx0IiwibG9jYWxlIjoiY3NfQ1oiLCJjb250ZW50Wm9uZXMiOltdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56LmN6L3Bhc3NlbmdlcmNhcnMvbWVyY2VkZXMtYmVuei1jYXJzL2Nhci1jb25maWd1cmF0b3IuaHRtbC9tb3Rvcml6YXRpb24vQ0NjaS9DWi9jcy9HTEItS0xBU1NFL09GRlJPQURFUj9pbnRlcm5hbF90ZXN0PXRydWUiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjY1In0sImZsYWdzIjp7InBhZ2VWaWV3Ijp0cnVlfSwidXNlciI6eyJhdHRyaWJ1dGVzIjp7ImdhQ2xpZW50SUQiOiIxMzgyMDIwODE4LjE3NDcxMjk0MjkifSwiYW5vbklkIjoiMWMwYzViYmM5MDdlMjQyYSJ9LCJwZXJmb3JtYW5jZSI6e30sImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX0sImNhdGFsb2ciOnt9LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjE4NjE2NjI0MDkxOTAyMjU2In0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x55f33640a7fa <unknown>
#1 0x55f335eaee90 <unknown>
#2 0x55f335e96156 <unknown>
#3 0x55f335e94a6a <unknown>
#4 0x55f335e951cf <unknown>
#5 0x55f335e95124 <unknown>
#6 0x55f335eb311f <unknown>
#7 0x55f335f583ca <unknown>
#8 0x55f335f26242 <unknown>
#9 0x55f335f4c135 <unknown>
#10 0x55f335f26013 <unknown>
#11 0x55f335ef2b3b <unknown>
#12 0x55f335ef37a1 <unknown>
#13 0x55f3363cfb9b <unknown>
#14 0x55f3363d3a8a <unknown>
#15 0x55f3363b7912 <unknown>
#16 0x55f3363d4604 <unknown>
#17 0x55f33639c74f <unknown>
#18 0x55f3363f8678 <unknown>
#19 0x55f3363f8856 <unknown>
#20 0x55f336409666 <unknown>
#21 0x7f711f29caa4 <unknown>
#22 0x7f711f329c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:19 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-Allure-Testing/QA-Allure-Testing/Tests/Last Configuration Completed_attempt_2.png'
ERROR    root:VerifyPersonalizationAndCapture.py:148 ❌ Image not found in the specified selector. Error: Message: