ERROR    root:ConfigCompleted.py:57 ❌ Error while performing configurator actions: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#cc-app-container-main > div.cc-app-container__main-frame.cc-grid-container > div.cc-app-container__navigation.ng-star-inserted > cc-navigation > nav > div > ul"}
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x55d0702e47fa <unknown>
#1 0x55d06fd88e90 <unknown>
#2 0x55d06fdda870 <unknown>
#3 0x55d06fddaa91 <unknown>
#4 0x55d06fdce446 <unknown>
#5 0x55d06fe0026d <unknown>
#6 0x55d06fdce2fa <unknown>
#7 0x55d06fe0040e <unknown>
#8 0x55d06fe26135 <unknown>
#9 0x55d06fe00013 <unknown>
#10 0x55d06fdccb3b <unknown>
#11 0x55d06fdcd7a1 <unknown>
#12 0x55d0702a9b9b <unknown>
#13 0x55d0702ada8a <unknown>
#14 0x55d070291912 <unknown>
#15 0x55d0702ae604 <unknown>
#16 0x55d07027674f <unknown>
#17 0x55d0702d2678 <unknown>
#18 0x55d0702d2856 <unknown>
#19 0x55d0702e3666 <unknown>
#20 0x7f82efe9caa4 <unknown>
#21 0x7f82eff29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_netherlands_prod?event=eyJpdGVtQWN0aW9uIjpudWxsLCJzb3VyY2UiOnsicGFnZVR5cGUiOiJkZWZhdWx0IiwibG9jYWxlIjoibmxfTkwiLCJjb250ZW50Wm9uZXMiOltdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lm5sL3Bhc3NlbmdlcmNhcnMvbWVyY2VkZXMtYmVuei1jYXJzL2Nhci1jb25maWd1cmF0b3IuaHRtbC9tb3Rvcml6YXRpb24vQ0NjaS9OTC9ubC9FLUtMQVNTRS9MSU1PVVNJTkU%2FaW50ZXJuYWxfdGVzdD10cnVlIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI1NyJ9LCJmbGFncyI6eyJwYWdlVmlldyI6dHJ1ZX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiODE2NTA0NTkuMTc0NzEzMzM0NCJ9LCJhbm9uSWQiOiJjYzBjNjE3N2U4ZTA4YjFiIn0sInBlcmZvcm1hbmNlIjp7fSwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfSwiY2F0YWxvZyI6e30sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiNDAzMzY1NDgxNzE5NDQ4MSJ9: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x55d0702e47fa <unknown>
#1 0x55d06fd88e90 <unknown>
#2 0x55d06fd70156 <unknown>
#3 0x55d06fd6ea6a <unknown>
#4 0x55d06fd6f1cf <unknown>
#5 0x55d06fd6f124 <unknown>
#6 0x55d06fd8d11f <unknown>
#7 0x55d06fe323ca <unknown>
#8 0x55d06fe00242 <unknown>
#9 0x55d06fe26135 <unknown>
#10 0x55d06fe00013 <unknown>
#11 0x55d06fdccb3b <unknown>
#12 0x55d06fdcd7a1 <unknown>
#13 0x55d0702a9b9b <unknown>
#14 0x55d0702ada8a <unknown>
#15 0x55d070291912 <unknown>
#16 0x55d0702ae604 <unknown>
#17 0x55d07027674f <unknown>
#18 0x55d0702d2678 <unknown>
#19 0x55d0702d2856 <unknown>
#20 0x55d0702e3666 <unknown>
#21 0x7f82efe9caa4 <unknown>
#22 0x7f82eff29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_netherlands_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gY2FyLWNvbmZpZ3VyYXRvciIsInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiODE2NTA0NTkuMTc0NzEzMzM0NCJ9LCJhbm9uSWQiOiJjYzBjNjE3N2U4ZTA4YjFiIn0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lm5sL3Bhc3NlbmdlcmNhcnMvbWVyY2VkZXMtYmVuei1jYXJzL2Nhci1jb25maWd1cmF0b3IuaHRtbC9tb3Rvcml6YXRpb24vQ0NjaS9OTC9ubC9FLUtMQVNTRS9MSU1PVVNJTkU%2FaW50ZXJuYWxfdGVzdD10cnVlIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI1NyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJwZXJmb3JtYW5jZSI6eyJzZGtQYXJzZVRpbWUiOjF9LCJfdG9vbHNFdmVudExpbmtJZCI6IjAxNDMxNDIyNTIxNDU5ODY4NiIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=136.0.7103.59)
Stacktrace:
#0 0x55d0702e47fa <unknown>
#1 0x55d06fd88e90 <unknown>
#2 0x55d06fd70156 <unknown>
#3 0x55d06fd6ea6a <unknown>
#4 0x55d06fd6f1cf <unknown>
#5 0x55d06fd6f124 <unknown>
#6 0x55d06fd8d11f <unknown>
#7 0x55d06fe323ca <unknown>
#8 0x55d06fe00242 <unknown>
#9 0x55d06fe26135 <unknown>
#10 0x55d06fe00013 <unknown>
#11 0x55d06fdccb3b <unknown>
#12 0x55d06fdcd7a1 <unknown>
#13 0x55d0702a9b9b <unknown>
#14 0x55d0702ada8a <unknown>
#15 0x55d070291912 <unknown>
#16 0x55d0702ae604 <unknown>
#17 0x55d07027674f <unknown>
#18 0x55d0702d2678 <unknown>
#19 0x55d0702d2856 <unknown>
#20 0x55d0702e3666 <unknown>
#21 0x7f82efe9caa4 <unknown>
#22 0x7f82eff29c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:19 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-Allure-Testing/QA-Allure-Testing/Tests/Last Configuration Completed_attempt_2.png'
ERROR    root:VerifyPersonalizationAndCapture.py:148 ❌ Image not found in the specified selector. Error: Message: