ERROR    root:ConfigCompleted.py:57 ❌ Error while performing configurator actions: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#cc-app-container-main > div.cc-app-container__main-frame.cc-grid-container > div.cc-app-container__navigation.ng-star-inserted > cc-navigation > nav > div > ul"}
  (Session info: chrome=135.0.7049.114); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x55add839175a <unknown>
#1 0x55add7e444b0 <unknown>
#2 0x55add7e959b3 <unknown>
#3 0x55add7e95bd1 <unknown>
#4 0x55add7e894b6 <unknown>
#5 0x55add7ebb5bd <unknown>
#6 0x55add7e8936a <unknown>
#7 0x55add7ebb75e <unknown>
#8 0x55add7ee15e0 <unknown>
#9 0x55add7ebb363 <unknown>
#10 0x55add7e87d63 <unknown>
#11 0x55add7e889c1 <unknown>
#12 0x55add8356a6b <unknown>
#13 0x55add835a951 <unknown>
#14 0x55add833eb62 <unknown>
#15 0x55add835b4c4 <unknown>
#16 0x55add832313f <unknown>
#17 0x55add837f6f8 <unknown>
#18 0x55add837f8d6 <unknown>
#19 0x55add83905a6 <unknown>
#20 0x7f97e229caa4 <unknown>
#21 0x7f97e2329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_romania_prod?event=eyJpdGVtQWN0aW9uIjpudWxsLCJzb3VyY2UiOnsicGFnZVR5cGUiOiJkZWZhdWx0IiwibG9jYWxlIjoicm9fUk8iLCJjb250ZW50Wm9uZXMiOltdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56LnJvL3Bhc3NlbmdlcmNhcnMvbWVyY2VkZXMtYmVuei1jYXJzL2Nhci1jb25maWd1cmF0b3IuaHRtbC9tb3Rvcml6YXRpb24vQ0NjaS9STy9yby9DLUtMQVNTRS9ULU1PREVMTCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjYifSwiZmxhZ3MiOnsicGFnZVZpZXciOnRydWV9LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjU1NjgxMjU0Mi4xNzQ2MzE4Mzk0In0sImFub25JZCI6ImU0OTI1ZWM0ODU3YjFkZjUifSwicGVyZm9ybWFuY2UiOnt9LCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9LCJjYXRhbG9nIjp7fSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI4NjQ2MTk2NDk4OTg1NDI3In0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.114)
Stacktrace:
#0 0x55add839175a <unknown>
#1 0x55add7e444b0 <unknown>
#2 0x55add7e2ad86 <unknown>
#3 0x55add7e2969a <unknown>
#4 0x55add7e29dff <unknown>
#5 0x55add7e29d54 <unknown>
#6 0x55add7e4869f <unknown>
#7 0x55add7eed92a <unknown>
#8 0x55add7ebb592 <unknown>
#9 0x55add7ee15e0 <unknown>
#10 0x55add7ebb363 <unknown>
#11 0x55add7e87d63 <unknown>
#12 0x55add7e889c1 <unknown>
#13 0x55add8356a6b <unknown>
#14 0x55add835a951 <unknown>
#15 0x55add833eb62 <unknown>
#16 0x55add835b4c4 <unknown>
#17 0x55add832313f <unknown>
#18 0x55add837f6f8 <unknown>
#19 0x55add837f8d6 <unknown>
#20 0x55add83905a6 <unknown>
#21 0x7f97e229caa4 <unknown>
#22 0x7f97e2329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_romania_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gY2FyLWNvbmZpZ3VyYXRvciIsInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiNTU2ODEyNTQyLjE3NDYzMTgzOTQifSwiYW5vbklkIjoiZTQ5MjVlYzQ4NTdiMWRmNSJ9LCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5yby9wYXNzZW5nZXJjYXJzL21lcmNlZGVzLWJlbnotY2Fycy9jYXItY29uZmlndXJhdG9yLmh0bWwvbW90b3JpemF0aW9uL0NDY2kvUk8vcm8vQy1LTEFTU0UvVC1NT0RFTEwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjY2IiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sInBlcmZvcm1hbmNlIjp7InNka1BhcnNlVGltZSI6NX0sIl90b29sc0V2ZW50TGlua0lkIjoiOTQ5MTc5ODA4MjkwNTU1NiIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.114)
Stacktrace:
#0 0x55add839175a <unknown>
#1 0x55add7e444b0 <unknown>
#2 0x55add7e2ad86 <unknown>
#3 0x55add7e2969a <unknown>
#4 0x55add7e29dff <unknown>
#5 0x55add7e29d54 <unknown>
#6 0x55add7e4869f <unknown>
#7 0x55add7eed92a <unknown>
#8 0x55add7ebb592 <unknown>
#9 0x55add7ee15e0 <unknown>
#10 0x55add7ebb363 <unknown>
#11 0x55add7e87d63 <unknown>
#12 0x55add7e889c1 <unknown>
#13 0x55add8356a6b <unknown>
#14 0x55add835a951 <unknown>
#15 0x55add833eb62 <unknown>
#16 0x55add835b4c4 <unknown>
#17 0x55add832313f <unknown>
#18 0x55add837f6f8 <unknown>
#19 0x55add837f8d6 <unknown>
#20 0x55add83905a6 <unknown>
#21 0x7f97e229caa4 <unknown>
#22 0x7f97e2329c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:127 ❌ Image not found in the specified selector. Error: Message: 

ERROR    root:VerifyPersonalizationAndCapture.py:18 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-Allure-Testing/QA-Allure-Testing/Tests/Last Configuration Completed_attempt_2.png'
ERROR    root:QAAppAllure.py:172 ❌ Test 'Last Configuration Completed' failed.