ERROR    root:ConfigCompleted.py:57 ❌ Error while performing configurator actions: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#cc-app-container-main > div.cc-app-container__main-frame.cc-grid-container > div.cc-app-container__navigation.ng-star-inserted > cc-navigation > nav > div > ul"}
  (Session info: chrome=135.0.7049.114); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x56176431875a <unknown>
#1 0x561763dcb4b0 <unknown>
#2 0x561763e1c9b3 <unknown>
#3 0x561763e1cbd1 <unknown>
#4 0x561763e104b6 <unknown>
#5 0x561763e425bd <unknown>
#6 0x561763e1036a <unknown>
#7 0x561763e4275e <unknown>
#8 0x561763e685e0 <unknown>
#9 0x561763e42363 <unknown>
#10 0x561763e0ed63 <unknown>
#11 0x561763e0f9c1 <unknown>
#12 0x5617642dda6b <unknown>
#13 0x5617642e1951 <unknown>
#14 0x5617642c5b62 <unknown>
#15 0x5617642e24c4 <unknown>
#16 0x5617642aa13f <unknown>
#17 0x5617643066f8 <unknown>
#18 0x5617643068d6 <unknown>
#19 0x5617643175a6 <unknown>
#20 0x7f7c9029caa4 <unknown>
#21 0x7f7c90329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_switzerland_prod?event=eyJpdGVtQWN0aW9uIjpudWxsLCJzb3VyY2UiOnsicGFnZVR5cGUiOiJkZWZhdWx0IiwibG9jYWxlIjoiaXRfQ0giLCJjb250ZW50Wm9uZXMiOltdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56LmNoL2l0L3Bhc3NlbmdlcmNhcnMvbWVyY2VkZXMtYmVuei1jYXJzL2Nhci1jb25maWd1cmF0b3IuaHRtbC9tb3Rvcml6YXRpb24vQ0NjaS9DSC9pdC9HTEItS0xBU1NFL09GRlJPQURFUiIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjAifSwiZmxhZ3MiOnsicGFnZVZpZXciOnRydWV9LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjExMDQwMDAuMTc0NjMwNjUzNiJ9LCJhbm9uSWQiOiI4MjZjNzA5OTNhMWI0ZTI2In0sInBlcmZvcm1hbmNlIjp7fSwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfSwiY2F0YWxvZyI6e30sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiOTcwNjQyMjc3NDkwMzc4NyJ9: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.114)
Stacktrace:
#0 0x56176431875a <unknown>
#1 0x561763dcb4b0 <unknown>
#2 0x561763db1d86 <unknown>
#3 0x561763db069a <unknown>
#4 0x561763db0dff <unknown>
#5 0x561763db0d54 <unknown>
#6 0x561763dcf69f <unknown>
#7 0x561763e7492a <unknown>
#8 0x561763e42592 <unknown>
#9 0x561763e685e0 <unknown>
#10 0x561763e42363 <unknown>
#11 0x561763e0ed63 <unknown>
#12 0x561763e0f9c1 <unknown>
#13 0x5617642dda6b <unknown>
#14 0x5617642e1951 <unknown>
#15 0x5617642c5b62 <unknown>
#16 0x5617642e24c4 <unknown>
#17 0x5617642aa13f <unknown>
#18 0x5617643066f8 <unknown>
#19 0x5617643068d6 <unknown>
#20 0x5617643175a6 <unknown>
#21 0x7f7c9029caa4 <unknown>
#22 0x7f7c90329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_switzerland_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gY2FyLWNvbmZpZ3VyYXRvciIsInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTEwNDAwMC4xNzQ2MzA2NTM2In0sImFub25JZCI6IjgyNmM3MDk5M2ExYjRlMjYifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouY2gvaXQvcGFzc2VuZ2VyY2Fycy9tZXJjZWRlcy1iZW56LWNhcnMvY2FyLWNvbmZpZ3VyYXRvci5odG1sL21vdG9yaXphdGlvbi9DQ2NpL0NIL2l0L0dMQi1LTEFTU0UvT0ZGUk9BREVSIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MCIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJwZXJmb3JtYW5jZSI6eyJzZGtQYXJzZVRpbWUiOjF9LCJfdG9vbHNFdmVudExpbmtJZCI6Ijc0Njg2NzM1NzY5MjU5NTkiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.114)
Stacktrace:
#0 0x56176431875a <unknown>
#1 0x561763dcb4b0 <unknown>
#2 0x561763db1d86 <unknown>
#3 0x561763db069a <unknown>
#4 0x561763db0dff <unknown>
#5 0x561763db0d54 <unknown>
#6 0x561763dcf69f <unknown>
#7 0x561763e7492a <unknown>
#8 0x561763e42592 <unknown>
#9 0x561763e685e0 <unknown>
#10 0x561763e42363 <unknown>
#11 0x561763e0ed63 <unknown>
#12 0x561763e0f9c1 <unknown>
#13 0x5617642dda6b <unknown>
#14 0x5617642e1951 <unknown>
#15 0x5617642c5b62 <unknown>
#16 0x5617642e24c4 <unknown>
#17 0x5617642aa13f <unknown>
#18 0x5617643066f8 <unknown>
#19 0x5617643068d6 <unknown>
#20 0x5617643175a6 <unknown>
#21 0x7f7c9029caa4 <unknown>
#22 0x7f7c90329c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:127 ❌ Image not found in the specified selector. Error: Message: 

ERROR    root:VerifyPersonalizationAndCapture.py:18 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-Allure-Testing/QA-Allure-Testing/Tests/Last Configuration Completed_attempt_2.png'
ERROR    root:QAAppAllure.py:172 ❌ Test 'Last Configuration Completed' failed.